---
- name: Install and Configure Portainer Agent Locally on Raspberry Pi
  hosts: localhost
  become: yes
  tasks:

    - name: Update and install dependencies
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - python3-pip
          - python3-docker  # Install Docker SDK via APT to avoid PEP 668 issues
        state: present
        update_cache: yes

    - name: Add Docker GPG Key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null
        chmod a+r /etc/apt/keyrings/docker.asc
      args:
        executable: /bin/bash

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Install Docker and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ensure Python Docker SDK is installed via PIP (forcing system-wide install)
      shell: "pip3 install --break-system-packages docker"

    - name: Deploy Portainer Agent container
      docker_container:
        name: portainer_agent
        image: portainer/agent:latest
        state: started
        restart_policy: always
        published_ports:
          - "9001:9001"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes:/var/lib/docker/volumes"

    - name: Verify Portainer Agent is running
      shell: "docker ps | grep portainer_agent"
      register: portainer_agent_status
      changed_when: false

    - name: Display Portainer Agent status
      debug:
        msg: "Portainer Agent is running! Add this node to Portainer using the IP: {{ ansible_default_ipv4.address }}:9001"
